server:
  port: 8080

spring:
  datasource:
    url: "jdbc:mysql://127.0.0.1:13306/test"
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    username: "test"
    password: "test123"
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comment: true
        type:
          descriptor:
            sql: DEBUG
logging:
  level:
    root: INFO