server:
  port: 8080

spring:
  profiles:
    active: default
  datasource:
    url: "jdbc:mysql://127.0.0.1:13306/test"
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    username: "test"
    password: "test123"
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true
        use_sql_comment: true
        type:
          descriptor:
            sql: DEBUG
logging:
  level:
    root: INFO

diary:
  post:
    image:
      base-path: "C:\\Data\\img"

---

server:
  port: 8181

spring:
  profiles: dev
  datasource:
    url: "jdbc:mysql://127.0.0.1:3306/test"

diary:
  post:
    image:
      base-path: "/home/ubuntu/data"